name = "ZeissMicroscopyFormat"
uuid = "5b7fe9ef-1e3c-4728-b6f6-0419187eab5e"
authors = ["Tim Holy <tim.holy@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
